name: Deploy to dev server

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NPM
        run: sudo apt-get install nodejs npm -y

      - name: Linter
        uses: moneyforward/jshint-action@v0

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_DOMAIN }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /srv/ianus
            git checkout dev
            git pull origin dev
            docker compose down
            docker compose up --build -d
